### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by kklinan** [simonstewart/swagger-to-PDF#10]
$  node index.js "swagger.json" 
[ 'swagger.json' ]
one
done
/home/XXX/Workspaces/open/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/dist/async.js:844
            if (fn === null) throw new Error("Callback was already called.");
                             ^
Error: Callback was already called.
    at /home/XXX/Workspaces/open/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/dist/async.js:844:36
    at /home/XXX/Workspaces/open/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/dist/async.js:3676:17
    at /home/XXX/Workspaces/open/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/dist/async.js:339:31
    at /home/XXX/Workspaces/open/swagger-to-PDF/node_modules/phantomjs-pdf/lib/phantomjs-pdf.js:119:8
    at FSReqWrap.wrapper [as oncomplete](fs.js:619:5)

**Comment by simonstewart** [comment]
kklinan

Were you able to find a resolution?
