### ISSUE TITLE
Cannot find module 'isexe'

### ISSUE THREAD

**Issue by vilakshanvarma** [simonstewart/swagger-to-PDF#8]
module.js:338
    throw err;
Error: Cannot find module 'isexe'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (workspace/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/phantomjs/node_modules/which/which.js:10:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by its-dibo** [comment]
did you resolved this issue?

**Comment by simonstewart** [comment]
Hi @eng-dibo, I'm not actively maintaining this library anymore.

**Comment by lxhmall** [comment]
Hello, have you solved the problem?, I had the same problem。。。
